### ISSUE TITLE
Nothing Shows in Document

### ISSUE THREAD

**Issue by James-Jamal** [schefa/Secretary#10]
After save a document , in document there is NO any document .
the document is saved but it does NOT shoe in Document page.
I clean site and admin caches I reinstall Secretary again and again but still same issue.
is there any solutions?

**Comment by schefa** [comment]
It is not quite clear what you mean.
If you have difficulties expressing yourself in english, please use https://www.deepl.com/translator

**Comment by James-Jamal** [comment]
sorry I'm typing with phone  , and it change words by itself,
1. first problem was  in contacts  , when I made a new document( invoice) , it didn't show the  document (invoice) in documents list 
but I found the problem , and it was my website local time needed to be change , after that time change it fixed.
2. second problem is when I go to edit a Document (invoice), the date will change to yesterday by itself ,
each time I have to change the date to today,
3/ another problem is in customer search when  I search a customer name it show up the name on the search bar and when I click on it, wont show anything in list (also with quick search with alphabets ) the  massage is "no results "
but this issue is for some customers name not all of them.
I hope you got it .
Thank you

**Comment by James-Jamal** [comment]
![untitled1](https://user-images.githubusercontent.com/44798021/48532675-61863780-e86f-11e8-96cf-f4280d13c3ca.jpg)
![untitled2](https://user-images.githubusercontent.com/44798021/48532689-6c40cc80-e86f-11e8-8566-191985afe8f7.jpg)

**Comment by James-Jamal** [comment]
I find the issue 
If there is a space before or after name or last name,  also on last name if there is a space between last name and middle name cause this issue in search result
need to change the name 
example
Name : john
Last name : Critz jr          we have to change this to Critz-jr

**Comment by James-Jamal** [comment]
is there any way to fix this searching issue .
It is hard to edit each contact .

**Comment by James-Jamal** [comment]
Thank you for very very very  good support and all your answers , just i cant see answers

**Comment by schefa** [comment]
Contacts Search improved in 3.2.11

Remember that this software is free of charge , therefore no support.
