### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by uwes2018** [schefa/Secretary#5]
Hi Schefa, I installed the component and the dashboard. My Joomla-Version is 3.8.10, php-version is 5.5.6.

Everything during the installation worked fine, but if I want to start the component I´m getting the following parse errror: Parse error: syntax error, unexpected '[' in /var/www/web17/html/administrator/components/com_secretary/application/helpers/messages.php on line 101. 

Line 101 has the following code: $cids  = [$user->id];

Please, could you help me? 

Thank you, and best regards

Uwe

**Comment by schefa** [comment]
Hallo Uwe,
den Fehler kann ich nicht reproduzieren. Der sollte auch in Kombination mit dem Modul "Nachrichten" auftreten.

Seit PHP5.4 wird auch die Notation von Arrays in der Form unterstützt sein. Testweise kannst du $cids  = array($user->id) ausprobieren

Wann genau tritt das auf? Auch auf der Startseite ..administrator/index.php?option=com_secretary

**Comment by uwes2018** [comment]
Hallo Fjodor,

wir haben jetzt eine neue php-Version auf dem Server, jetzt geht es. Wenn ich allerdings bei den Einstellungen etwas ändern und speichern möchte, z.B. die pdf-library, dann wird eine Download-ID verlangt, die es ja jetzt nicht mehr gibt. Was mache ich da?

Danke und viele Grüße

Uwe

**Comment by schefa** [comment]
einfach irgendwas eingeben. Das mit der Download ID wird noch entfernt

**Comment by schefa** [comment]
das mit der download id wurde in 3.2.7 entfernt. Du kannst da ansonsten auch was beliebiges eingeben. Ist obsolet

**Comment by uwes2018** [comment]
Hi Schefa, danke für die Zeit und die Hilfe. Es läuft soweit. Nur eine Frage: ist es möglich die Produkte oder andere Komponenten in das Frontend zu integrieren?

Beste Grüße

Uwe
