### ISSUE TITLE
invoice paid amount

### ISSUE THREAD

**Issue by shihsaway** [schefa/Secretary#6]
hi
i want to show paid amount in invoice pdf and also it will be great to show remaining 
i am not a programmer but if you can guide me with files i should change it will will be great

**Comment by schefa** [comment]
There is the feature of "templates" in Secretary, where you can output any content of a document through datafields.

https://www.schefa.com/en/secretary/docs/secretary-templates

**Comment by shihsaway** [comment]
i am aware of the template  feature but there is no data field to call pay amount 
also there is no remain amount in the invoice

**Comment by schefa** [comment]
now I unterstand

**Comment by schefa** [comment]
done in 3.2.8

here are the fields:
{paid}
{total-remaining}
