### ISSUE TITLE
Problem with map on contact page

### ISSUE THREAD

**Issue by INOPIAE** [schefa/Secretary#8]
The map on the contact page shows the error "For development purpose only".
Next it shows a popup from Google
![image](https://user-images.githubusercontent.com/2772829/46556889-4b886d00-c8e8-11e8-8ad8-c9c52a8f77f8.png)
What can be done?

**Comment by schefa** [comment]
You need an API Key from Google and put it in the configuration of Secretary.
![mapsapikey](https://user-images.githubusercontent.com/9777281/46840069-93643400-cdc1-11e8-9469-eaa6a7af8f97.PNG)

This is where it can be found in the Google Developer Console.
![mapsapikey2](https://user-images.githubusercontent.com/9777281/46840071-93643400-cdc1-11e8-8039-177f792baf18.PNG)
