### ISSUE TITLE
pdf viewing issue

### ISSUE THREAD

**Issue by James-Jamal** [schefa/Secretary#9]
after each document save page going to a blank page with error 500 , but file will save
mydomain.com/administrator/index.php?option=com_secretary&view=document&layout=edit&id=0

2 . I cant see PDF file in documents for each invoice , the iframe is blank after push the pdf icon , but print icon for preview shows the invoice .
how can i fix it?

**Comment by James-Jamal** [comment]
1. after each document save page going to a blank page with error 500 , but file saved
2 . I cant see PDF file in documents for each invoice , the iframe is blank after push the pdf icon , but print icon for preview shows the invoice .
how can i fix it

**Comment by schefa** [comment]
what PHP version do you use? What PDF library and version? mpdf? dompdf?

**Comment by James-Jamal** [comment]
after I install dompdf  this problem fixed  but still has same issue when I click on the pdf icon,
Iframe doesn't show the pdf  it shows bunch off letters 
when I download the file, pdf file is fine

**Comment by James-Jamal** [comment]
> what PHP version do you use? What PDF library and version? mpdf? dompdf?
PHP version, 5.6.38 
cpanel

**Comment by James-Jamal** [comment]
![untitled1](https://user-images.githubusercontent.com/44798021/48565344-54e0fe00-e8c6-11e8-91dd-49e88616b798.jpg)

**Comment by James-Jamal** [comment]
This issue fixed with mpdf 6 ,    v6.1.4
Thank You
